[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jc-dt"
version = "0.1.0"
description = "A utility for parsing dates and times and performing operations on them."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Jeff Clough", email = "jeff@cloughcottage.com" }
]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
]
dependencies = [
    "parsedatetime",
    "jc-debug",
    "jc-handy-helpers",
]

[project.scripts]
dt= "dt.main:main"

[tool.setuptools.packages.find]
where = ["src"]
